### ISSUE TITLE
Error on installing dependencies

### ISSUE THREAD

**Issue by njanmelbin** [diegohaz/generator-rest#39]
I am getting error on entering `yo rest` . It installs dependencies but towards the end it gives error.

I am using windows 8.1 

```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Thomas\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "intall"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.6
npm ERR! path C:\Users\Thomas\my-api\node_modules\.staging\jsonpointer-10566ae3
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Thomas\my-api\node_modules\.staging\jsonpointer-10566ae3' -> 'C:\User\Thomas\my-api\node_modules\jsonpointer'
npm ERR!     at destStatted (C:\Users\Thomas\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Thomas\my-api\node_modules\.staging\jsonpointer-10566ae3' -> 'C:\User\Thomas\my-api\node_modules\jsonpointer'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\Thomas\my-api\node_modules\.staging\jsonpointer-10566ae3' -> 'C:\Uers\Thomas\my-api\node_modules\jsonpointer'
npm ERR!     at destStatted (C:\Users\Thomas\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Thomas\my-api\node_modules\.staging\jsonpointer-10566ae3' -> 'C:\User\Thomas\my-api\node_modules\jsonpointer'
npm ERR!     at Error (native) parent: 'my-api' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Thomas\my-api\npm-debug.log

```

**Comment by diegohaz** [comment]
Hi, @njanmelbin 

Take a look at this issue and see if some of the solutions solves your problem: https://github.com/npm/npm/issues/10826

**Comment by njanmelbin** [comment]
I got previous error cleared by changing version of npm but new error has occured

```
(node:8384) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

> bcrypt@0.8.7 install C:\Users\Thomas\my-api\node_modules\bcrypt
> node-gyp rebuild


C:\Users\Thomas\my-api\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Users\Thomas\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
(node:8104) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 64-bit node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Users\Thomas\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\install.js:403:20)
gyp ERR! stack     at emitOne (events.js:101:20)
gyp ERR! stack     at Request.emit (events.js:188:7)
gyp ERR! stack     at Request.onRequestResponse (C:\Users\Thomas\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:985:10)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Thomas\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Thomas\my-api\node_modules\bcrypt
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Thomas\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Thomas\my-api\npm-debug.log

```

**Comment by diegohaz** [comment]
Hey, @njanmelbin . I'm gonna close this because this is not directly related to this generator. The problem might be related to `bcrypt` installation on Windows. Take a look at the [bcrypt issues](https://github.com/kelektiv/node.bcrypt.js/issues).
